name: Compare with Upstream

on:
  schedule:
    - cron: "0 * * * *"
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compare-with-upstream:
    name: Compare with Upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Enable Corepack
        run: "corepack enable"

      - name: Install step
        run: "yarn install"

      - name: Compare with Upstream
        run: "yarn run docs:compare-with-upstream"
