name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Checkout Submodules
        run: git submodule init && git submodule update

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "yarn install"

      - name: Build step
        run: "yarn run docs:build"

      - run: "cp -r docs/.vitepress/dist hosting-server/public"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vrchat-docs-localization"
          entrypoint: "main.ts"
          root: "hosting-server"
