name: Docs Lint Check

on:
  push:
  pull_request:

jobs:
  docs-lint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: corepack enable && yarn install

      - name: Lint Check
        run: yarn run docs:lint
