name: Markdownlint Check

on:
  push:
  pull_request:

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: corepack enable && yarn install

      - name: Markdownlint Check
        run: yarn run docs:markdownlint
